version = 2

[module]
type = "android-app"
name = "app"
languageLevel = "JAVA_8"
output = "build/classes"

[sourceSets.debug]
scope = "IMPLEMENTATION"
aidl = ["src/debug/aidl"]
assets = ["src/debug/assets"]
java = ["src/debug/java", "src/debug/kotlin"]
jniLibs = ["src/debug/jniLibs"]
res = ["src/debug/res"]
resources = ["src/debug/resources"]

[sourceSets.main]
scope = "IMPLEMENTATION"
aidl = ["src/main/aidl"]
assets = ["src/main/assets"]
java = ["src/main/java", "src/main/kotlin"]
jniLibs = ["src/main/jniLibs"]
res = ["src/main/res"]
resources = ["src/main/resources"]

[sourceSets.release]
scope = "IMPLEMENTATION"
aidl = ["src/release/aidl"]
assets = ["src/release/assets"]
java = ["src/release/java", "src/release/kotlin"]
jniLibs = ["src/release/jniLibs"]
res = ["src/release/res"]
resources = ["src/release/resources"]

[dependencies]
implementation = ["androidx.appcompat:appcompat:1.7.1", "com.google.android.material:material:1.12.0", "com.github.bumptech.glide:glide:4.16.0", "com.google.code.gson:gson:2.11.0", "com.squareup.okhttp3:okhttp:4.12.0"]

[android]
namespace = "com.yuvextech.NurAi"
compileSdk = 34
minSdk = 23
targetSdk = 34
manifest = "src/main/AndroidManifest.xml"
versionCode = 1
versionName = "1.0.0"
isApplication = true
manifestPlaceholders = []
buildTypes = [{ name = "release", debuggable = false, minifyEnabled = false, shrinkResources = false, proguardFiles = ["proguard-android-optimize.txt", "proguard-rules.pro"], signingConfig = "release-key" }]
kspProcessors = ["glide"]
